apiVersion: v1
kind: ConfigMap
metadata:
  name: bankpack-spending-config
data:
  SERVLET_CONTEXT_PATH: "/spending"
# MYSQL DB
  DB_SERVER: mysql.mysql
  DB_PORT: "3306"
  DB_USERNAME: saju
  DB_PASSWORD: saju
